export type InsightLocale = "tr" | "en";

type LocalizedText = Record<InsightLocale, string>;

export type InsightArticle = {
  slug: string;
  category: LocalizedText;
  title: LocalizedText;
  description: LocalizedText;
  intro: LocalizedText;
  publishedAt: string;
  updatedAt: string;
  sections: Array<{ heading: LocalizedText; body: LocalizedText }>;
  takeaways: Record<InsightLocale, string[]>;
  sources: Array<{ label: string; url: string }>;
};

export const insights: InsightArticle[] = [
  {
    slug: "ptf-market-clearing-price",
    category: { tr: "Türkiye Elektrik Piyasası", en: "Türkiye Electricity Market" },
    title: { tr: "PTF, GİP, YEKDEM ve Dengesizlik: Elektrik Maliyetini Okuma Rehberi", en: "PTF, Intraday Trading, YEKDEM and Imbalance: A Practical Cost Guide" },
    description: { tr: "Türkiye elektrik piyasasındaki temel fiyat ve maliyet göstergelerini aynı karar çerçevesinde, örnek hesap ve kontrol listeleriyle değerlendirin.", en: "Evaluate Türkiye's core electricity price and cost signals in one decision framework with worked examples and control checks." },
    intro: { tr: "Bir sanayi tesisinin elektrik maliyeti yalnızca Piyasa Takas Fiyatı'ndan oluşmaz. Saatlik tüketim profili, tedarik sözleşmesi, Gün İçi Piyasası işlemleri, dengesizlik, YEKDEM ve düzenlenen bedeller farklı zamanlarda toplam sonucu etkiler. Bu rehber, göstergeleri birbirine karıştırmadan okumak ve bir maliyet analizi kurmak için gereken veri sınırlarını açıklar.", en: "An industrial facility's electricity cost is not the Market Clearing Price alone. Its hourly load profile, supply contract, intraday trades, imbalance exposure, YEKDEM and regulated charges affect the final result on different timelines. This guide explains the data boundaries needed to read those signals without mixing unlike values." },
    publishedAt: "2026-08-26",
    updatedAt: "2026-09-02",
    sections: [
      {
        heading: { tr: "PTF neyi gösterir, neyi göstermez?", en: "What PTF shows—and what it does not" },
        body: { tr: "PTF, Gün Öncesi Piyasası'nda her teslimat saati için arz ve talep tekliflerinin piyasa kuralları altında eşleşmesiyle oluşan referans fiyattır. Bir gün içinde farklı saatlerde farklı PTF değerleri bulunur. Bu değer, tesisin o saatte gerçekten ödediği nihai birim fiyat değildir. Tedarikçinin marjı, sözleşme formülü, dengesizlik yaklaşımı, YEKDEM ve düzenlenen tarife kalemleri ayrıca ele alınır. Bu nedenle aylık basit PTF ortalamasını faturayla doğrudan karşılaştırmak çoğu zaman yanlış sonuç verir. Doğru başlangıç, saatlik PTF'yi aynı saatlerdeki ölçülmüş tüketimle ağırlıklandırmaktır.", en: "PTF is the reference price formed for every delivery hour in the Day-Ahead Market when supply and demand bids clear under market rules. A day therefore contains many hourly prices. PTF is not the final unit price paid by a facility: supplier margin, contract formula, imbalance treatment, YEKDEM and regulated tariff items are separate. Comparing a simple monthly PTF average directly with a bill can therefore be misleading. A better starting point is to weight hourly PTF by the facility's measured consumption in those same hours." },
      },
      {
        heading: { tr: "GİP ve dengesizlik maliyeti nerede devreye girer?", en: "Where intraday trading and imbalance enter the picture" },
        body: { tr: "Gün Öncesi programı kesinleştikten sonra üretim veya tüketim beklentisi değişebilir. Gün İçi Piyasası, katılımcıların teslimata daha yakın zamanda pozisyonunu düzeltmesine imkân verir; dengesizlik ise gerçekleşen durum ile program arasındaki farkın uzlaştırma etkisidir. GİP fiyatını PTF ile aynı seri gibi toplamak yerine her işlemin hacmi, yönü ve zamanı saklanmalıdır. Bir tesis doğrudan piyasa katılımcısı değilse bu risk sözleşmede tedarikçi tarafından fiyatlanabilir. Analizde önce ticari sorumluluğun kimde olduğu, sonra hangi fiyat formülünün uygulandığı doğrulanmalıdır.", en: "Generation or demand expectations can change after the day-ahead position is fixed. The Intraday Market allows participants to adjust closer to delivery, while imbalance settlement addresses the difference between scheduled and actual positions. Intraday prices should not simply be appended to the PTF series: transaction volume, direction and timestamp must remain attached. If a facility is not a direct market participant, the supplier may price that risk into the contract. The analysis should first establish who carries the commercial responsibility and then verify the applicable pricing formula." },
      },
      {
        heading: { tr: "Tüketim ağırlıklı maliyet için örnek yöntem", en: "Worked method for a load-weighted cost" },
        body: { tr: "Basitleştirilmiş enerji bedeli için her saat tüketim (MWh) ile aynı saatin PTF değeri (TL/MWh) çarpılır; saatlik tutarlar toplanır ve toplam MWh'ye bölünür. Örneğin düşük fiyatlı bir saatte 1 MWh, yüksek fiyatlı bir saatte 3 MWh tüketen tesisin ağırlıklı fiyatı iki saatin basit ortalamasından yüksek çıkar. Bu yalnızca enerji bileşeni için bir kontrol hesabıdır. Kayıp katsayısı, marj, vergi, dağıtım ve diğer sözleşme kalemleri eklenmeden nihai fatura sonucu olarak sunulmamalıdır. Ölçüm aralıkları 15 dakika ise saatlik toplama kuralı da belgelenmelidir.", en: "For a simplified energy component, multiply each hour's consumption in MWh by that hour's PTF in TRY/MWh, sum the hourly costs, and divide by total MWh. A facility using 1 MWh in a low-price hour and 3 MWh in a high-price hour will have a weighted price above the simple two-hour average. This is only a control calculation for the energy component. It must not be presented as a final bill before loss factors, margin, taxes, network charges and contractual items are added. If meters record 15-minute intervals, the hourly aggregation rule should also be documented." },
      },
      {
        heading: { tr: "YEKDEM ve fatura kalemlerini ayrı izleyin", en: "Track YEKDEM and bill components separately" },
        body: { tr: "YEKDEM birim maliyeti dönemsel olarak yayımlanan ve tedarik yapısına göre faturaya yansıyabilen ayrı bir göstergedir. PTF'nin içine gömülü varsayılmamalı, ilgili dönem ve sözleşme maddesiyle eşleştirilmelidir. Dağıtım bedeli, güç/aşım, reaktif enerji, vergi ve fonlar da aynı veri türü değildir. Profesyonel bir fatura kontrol tablosu her kalem için kaynak belgeyi, ölçü birimini, dönemi, hesap formülünü ve toleransı ayrı sütunda tutar. Böylece piyasa hareketi, tesis davranışı ve faturalama farkı birbirinden ayrılabilir.", en: "The YEKDEM unit cost is a separately published periodic indicator that may flow into bills depending on the supply structure. It should not be assumed to be embedded in PTF; match it to the relevant period and contract clause. Network charges, capacity or overrun items, reactive energy, taxes and levies are different data types again. A professional bill-control table keeps the source document, unit, period, formula and tolerance for each line item. That separation helps distinguish market movement, facility behaviour and a possible billing discrepancy." },
      },
      {
        heading: { tr: "Veri kalite kontrolleri", en: "Data-quality controls" },
        body: { tr: "Fiyat ve tüketim serileri aynı saat diliminde, aynı teslimat gününde ve aynı aralık uzunluğunda olmalıdır. Eksik sayaç aralığı, tekrar eden zaman damgası, yaz saati geçişi ve kWh–MWh dönüşümü işaretlenmeden maliyet hesabı çalıştırılmamalıdır. Sıfır tüketim ile eksik veri ayrılmalı; tahmini kayıtlar ham ölçümün üzerine yazılmamalıdır. PTF veya YEKDEM verisinin sonradan revize edilebileceği unutulmamalı, raporda sorgu zamanı ve kaynak sürümü saklanmalıdır. STR Energy Piyasa Veri Projesi kaynak ve sorgu zamanını görünür tutar; nihai ticari kontrol yine resmi kayıtla yapılır.", en: "Price and consumption series must share the same time zone, delivery day and interval length. Do not run the cost calculation before flagging missing meter intervals, duplicate timestamps, daylight-saving transitions and kWh-to-MWh conversion. Separate measured zero from missing data, and never overwrite raw measurements with estimates. PTF or YEKDEM history may later be revised, so retain query time and source version in the report. The STR Energy Market Data Project keeps the source and query time visible; final commercial verification still belongs against official records." },
      },
      {
        heading: { tr: "Karar öncesi kısa kontrol listesi", en: "Pre-decision checklist" },
        body: { tr: "Önce analiz amacını yazın: fatura doğrulama, bütçe, vardiya planlama veya sözleşme karşılaştırması. Ardından tesisin zaman dilimini ve sayaç birimini doğrulayın; saatlik tüketim ile fiyatı birincil anahtar üzerinden eşleştirin; eksik aralık oranını raporlayın; sözleşme formülünü ve risk paylaşımını belgeleyin; YEKDEM ile düzenlenen kalemleri ayrı ekleyin; sonucu resmi fatura ve EPİAŞ kaydıyla örnek dönem üzerinde test edin. Bir fark bulunduğunda önce veri hizalamasını, sonra formülü, en son ticari uyuşmazlığı araştırmak hatalı alarmı azaltır.", en: "Write down the decision first: bill validation, budgeting, shift scheduling or contract comparison. Then verify the facility time zone and meter unit; join hourly load and price on an explicit timestamp; report missing-interval coverage; document the contract formula and risk allocation; add YEKDEM and regulated items separately; and test the result against an official bill and EPİAŞ record for a sample period. When a difference appears, investigate data alignment first, the formula second and a commercial dispute last. This order reduces false alarms." },
      },
    ],
    takeaways: { tr: ["PTF nihai fatura fiyatı değil, saatlik piyasa referansıdır.", "Maliyet hesabı saatlik tüketimle ağırlıklandırılmalı ve diğer kalemler ayrı tutulmalıdır.", "Eksik veri, saat dilimi ve sözleşme sınırı doğrulanmadan karar verilmemelidir."], en: ["PTF is an hourly market reference, not the final bill price.", "Weight cost by hourly consumption and keep other charges separate.", "Verify missing data, time zones and contract boundaries before acting."] },
    sources: [
      { label: "EPİAŞ — Şeffaflık Platformu", url: "https://seffaflik.epias.com.tr/" },
      { label: "EPİAŞ — Gün Öncesi Piyasası", url: "https://www.epias.com.tr/gun-oncesi-piyasasi/genel-esaslar/" },
      { label: "EPİAŞ — Gün İçi Piyasası", url: "https://www.epias.com.tr/gun-ici-piyasasi/genel-esaslar/" },
      { label: "EPİAŞ — Enerji Dengesizliklerinin Uzlaştırması", url: "https://www.epias.com.tr/uzlastirma/enerji-dengesizliklerinin-uzlastirmasi/" },
    ],
  },
  {
    slug: "entsoe-day-ahead-prices",
    category: { tr: "Avrupa ve Küresel Elektrik Verisi", en: "European and Global Electricity Data" },
    title: { tr: "ENTSO-E Elektrik Verilerini Doğru Karşılaştırma Rehberi", en: "How to Compare ENTSO-E Electricity Data Correctly" },
    description: { tr: "Gün öncesi fiyat, üretim, yük, sınır ötesi akış, MW ve MWh serilerini doğru zaman ve kapsam sınırlarıyla karşılaştırın.", en: "Compare day-ahead price, generation, load, cross-border flow, MW and MWh series with correct time and scope boundaries." },
    intro: { tr: "ENTSO-E Şeffaflık Platformu Avrupa elektrik sistemini anlamak için güçlü bir kaynaktır; ancak aynı tarih aralığını seçmek tek başına karşılaştırılabilirlik sağlamaz. Teklif bölgesi, saat dilimi, para birimi, ölçüm türü, veri çözünürlüğü ve revizyon durumu sonuçları değiştirebilir. Bu rehber, fiyatı fiziksel sistem verileriyle birlikte okumak için tekrarlanabilir bir yöntem sunar.", en: "The ENTSO-E Transparency Platform is a powerful source for understanding Europe's power system, but choosing the same dates does not by itself make two series comparable. Bidding zone, time zone, currency, measurement type, resolution and revision status can all change the result. This guide gives a repeatable method for reading prices alongside physical system data." },
    publishedAt: "2026-08-26",
    updatedAt: "2026-09-02",
    sections: [
      {
        heading: { tr: "Ülke ile teklif bölgesini karıştırmayın", en: "Do not confuse a country with a bidding zone" },
        body: { tr: "Gün öncesi fiyatlar çoğu zaman siyasi ülke sınırından ziyade teklif bölgesi düzeyinde yayımlanır. Bazı ülkelerde birden fazla bölge bulunabilir; bazı piyasa alanları ise bağlantı veya istisna nedeniyle beklenenden farklı kodlanabilir. Analiz tablosunda görünen kısa ülke etiketini doğrudan hukuki ülke toplamı saymak yerine kullanılan EIC alan kodunu ve veri açıklamasını kaydedin. Fiyat, yük ve üretim serilerini birleştirirken her üçünün de aynı coğrafi kapsamı temsil ettiğini doğrulayın. Aksi halde doğru görünen grafik aslında farklı sistem sınırlarını karşılaştırabilir.", en: "Day-ahead prices are commonly published for bidding zones rather than political country boundaries. Some countries contain several zones, while particular market areas may use codes that differ from an intuitive country label. Record the EIC area code and dataset definition instead of treating a short label as a legal-country total. When joining price, load and generation, confirm that all three represent the same geographic scope. A chart can look internally consistent while comparing different system boundaries." },
      },
      {
        heading: { tr: "Saat dilimi, çözünürlük ve yaz saati", en: "Time zones, resolution and daylight saving" },
        body: { tr: "ENTSO-E belgeleri dönemleri UTC tabanlı isteklerle ele alabilirken piyasa teslimatı yerel saat düzenine bağlıdır. Yaz saati geçiş günlerinde 23 veya 25 saatlik yerel gün oluşabilir; sabit 24 satır varsayımı veri kaybına veya yinelenen saate yol açar. Serilerin 15, 30 veya 60 dakikalık çözünürlükleri de farklı olabilir. Önce zaman damgalarını ortak bir zaman eksenine dönüştürün, özgün zaman dilimini saklayın ve yalnızca açık bir toplama kuralı tanımlandıysa daha geniş aralığa dönüştürün. Grafik etiketinde dönem sonunun dahil olup olmadığı da belirtilmelidir.", en: "ENTSO-E requests may use UTC-based periods while market delivery follows local-clock conventions. A daylight-saving transition can create a 23- or 25-hour local day, so assuming exactly 24 rows risks dropped or duplicated hours. Series may also use 15-, 30- or 60-minute resolution. Convert timestamps to a common time axis, retain the original zone and aggregate only under an explicit rule. The chart should also state whether the period end is inclusive or exclusive." },
      },
      {
        heading: { tr: "Fiyatı üretim ve yükle birlikte okuma", en: "Read price with generation and load" },
        body: { tr: "Tek bir yüksek fiyat saati tek başına neden açıklamaz. Aynı zaman ekseninde gerçekleşen yükü, üretim türlerini, santral kullanılabilirliğini ve komşu bölgelerle fiziksel akışı incelemek gerekir. Yük artışı, düşük marjlı üretim, yenilenebilir düşüşü veya iletim kısıtı benzer fiyat sonucu üretebilir. Korelasyon, nedensellik kanıtı değildir; olay açıklaması için resmi piyasa duyuruları ve sistem koşulları ayrıca kontrol edilmelidir. Analizin amacı fiyat tahmini ise geçmiş veriyle eğitim ve test dönemlerinin ayrılması gerekir; açıklama amacıyla kurulan grafik doğrudan tahmin modeli sayılmaz.", en: "A single high-price hour does not explain its own cause. Align actual load, generation by type, plant availability and physical flows with neighbouring areas on the same time axis. Demand growth, tight dispatchable supply, reduced renewable output or transmission constraints can produce a similar price outcome. Correlation is not proof of causation; official market notices and system conditions should be checked for an event explanation. If the objective is forecasting, separate historical training and test periods—a descriptive chart is not automatically a forecast model." },
      },
      {
        heading: { tr: "MW, MWh ve kapasite faktörü", en: "MW, MWh and capacity factor" },
        body: { tr: "MW belirli andaki güç veya kurulu kapasiteyi, MWh ise bir zaman aralığındaki enerji miktarını ifade eder. 100 MW kurulu güce sahip tesisin bir saatte 100 MWh üretmesi teorik üst sınıra yakın çalıştığını gösterebilir; aynı santralin bir yıldaki üretimi bakım, kaynak ve kısıtlar nedeniyle çok daha düşük kapasite faktörü verir. Ülke karşılaştırmasında kurulu gücü yıllık üretimle doğrudan sıralamak yerine teknoloji bazında kapasite faktörü, net/brüt tanımı ve veri dönemini kontrol edin. Negatif fiyat veya negatif akış da otomatik olarak hatalı kayıt değildir; piyasa ve yön tanımı incelenmelidir.", en: "MW describes instantaneous power or installed capacity; MWh describes energy over an interval. A 100 MW plant producing close to 100 MWh in one hour may be near its theoretical maximum for that hour, while its annual generation can imply a much lower capacity factor because of maintenance, resource availability and constraints. For country comparisons, do not rank installed capacity directly against annual output without checking technology-level capacity factors, net/gross definitions and period. A negative price or signed flow is not automatically an error either; inspect the market and direction convention." },
      },
      {
        heading: { tr: "Sınır ötesi akışlarda yön ve işaret", en: "Direction and sign in cross-border flows" },
        body: { tr: "Fiziksel akış verisi, iki alan arasındaki ölçülen veya hesaplanan enerji yönünü temsil eder; ticari programla her zaman aynı olmayabilir. A→B sorgusu ile B→A sorgusunu aynı seri olarak kabul etmeyin. Kaynağın işaret kuralını, giriş-çıkış alanını ve ölçüm birimini kaydedin. Net akış hesaplanacaksa iki yönün zaman çözünürlüğü eşit olmalı ve eksik kayıtlar sıfır kabul edilmemelidir. Fiyat farkı ile akış yönü birlikte yorumlanabilir, ancak iletim kaybı, kapasite tahsisi ve sistem güvenliği koşulları görülmeden arbitraj sonucu çıkarılmamalıdır.", en: "Physical-flow data represents measured or calculated energy direction between two areas and may not equal commercial schedules. Do not treat an A-to-B request as identical to B-to-A. Record the provider's sign convention, in-area, out-area and unit. If calculating net flow, both directions must share a resolution and missing records must not become zero. Price spreads and flow direction can be considered together, but transmission losses, capacity allocation and security constraints must be understood before drawing an arbitrage conclusion." },
      },
      {
        heading: { tr: "Tekrarlanabilir karşılaştırma kontrolü", en: "A reproducible comparison checklist" },
        body: { tr: "Karşılaştırmadan önce veri seti adı, EIC alan kodu, başlangıç-bitiş zamanı, saat dilimi, çözünürlük, birim ve sorgu zamanını kaydedin. Ham yanıtı koruyun; temizlenmiş tabloya uygulanan toplama, para birimi dönüşümü veya eksik veri işlemini ayrı bir işlem günlüğünde tutun. En az bir günü resmi arayüzde elle doğrulayın. Farklı sağlayıcılarla karşılaştırıyorsanız tanımların aynı olduğunu varsaymayın. STR Energy Piyasa Veri Projesi kaynak ve kayıt sayısını dışa aktarıma ekler; kullanıcı yine de resmi kaynaktaki revizyon ve kapsam notlarını kontrol etmelidir.", en: "Before comparison, record the dataset name, EIC area code, start and end time, time zone, resolution, unit and query time. Keep the raw response and log any aggregation, currency conversion or missing-data treatment separately from the cleaned table. Manually reconcile at least one day with the official interface. If another provider is involved, do not assume its definitions match. STR Energy Market Data Project includes source and row count in exports; users should still check official revision and scope notes." },
      },
    ],
    takeaways: { tr: ["Aynı tarih aralığı, tek başına karşılaştırılabilirlik sağlamaz.", "Fiyat, üretim, yük ve akış aynı coğrafya ve zaman ekseninde hizalanmalıdır.", "Ham veri ve dönüşüm günlüğü korunmadan sonuç denetlenebilir değildir."], en: ["Matching dates alone do not guarantee comparability.", "Align price, generation, load and flows to the same geography and time axis.", "A result is not auditable without raw data and a transformation log."] },
    sources: [
      { label: "ENTSO-E — Transparency Platform", url: "https://transparency.entsoe.eu/" },
      { label: "ENTSO-E — Transparency Platform Data Items", url: "https://www.entsoe.eu/data/transparency-platform/" },
      { label: "U.S. EIA — Electricity explained", url: "https://www.eia.gov/energyexplained/electricity/" },
    ],
  },
  {
    slug: "industrial-energy-management",
    category: { tr: "Endüstriyel Enerji Yönetimi", en: "Industrial Energy Management" },
    title: { tr: "Endüstriyel Enerji Yönetimi: Ölçümden Doğrulanmış Aksiyona", en: "Industrial Energy Management: From Measurement to Verified Action" },
    description: { tr: "Sayaç hiyerarşisi, veri kalitesi, baz yük, güç kalitesi, aksiyon sahipliği ve tasarruf doğrulamasını tek çalışma düzeninde kurun.", en: "Build one operating method for meter hierarchy, data quality, baseload, power quality, action ownership and savings verification." },
    intro: { tr: "Enerji yönetimi aylık faturayı izlemekten ibaret değildir. Güvenilir ölçüm, üretim bağlamı, açık sorumluluk ve uygulama sonrası doğrulama aynı döngüde çalışmadığında gösterge panelleri kalıcı iyileştirme üretmez. Bu rehber, ana sayaçtan ekipman seviyesine uzanan veriyi operasyonel karara dönüştürmek için pratik bir çerçeve sunar.", en: "Energy management is more than reviewing a monthly bill. Dashboards do not create durable improvement unless reliable measurement, production context, clear ownership and post-action verification operate in one cycle. This guide presents a practical framework for turning data from the main meter down to equipment level into operational decisions." },
    publishedAt: "2026-08-26",
    updatedAt: "2026-09-02",
    sections: [
      { heading: { tr: "Ölçüm sınırı ve sayaç hiyerarşisi", en: "Measurement boundary and meter hierarchy" }, body: { tr: "Önce hangi fiziksel ve idari sınırın yönetildiği belirlenir: tüm tesis, üretim hattı, yardımcı işletme veya ekipman. Ana sayaç toplamı verir fakat nedeni göstermez. Alt sayaçlar; basınçlı hava, soğutma, fırın, pompa, HVAC ve üretim hatlarını ayırabilir. Sayaç ağacında her alt toplamın hangi üst sayaca bağlandığı, çarpan, birim ve örnekleme aralığı belgelenmelidir. Alt sayaç toplamı ile ana sayaç arasında fark varsa teknik kayıp, kapsanmayan yük, saat kayması ve ölçüm hatası ayrı ayrı araştırılır; fark otomatik olarak kaçak veya tasarruf fırsatı sayılmaz.", en: "First define the physical and organisational boundary: whole site, production line, utility system or equipment. A main meter gives the total but not the cause. Submetering can separate compressed air, cooling, furnaces, pumps, HVAC and lines. Document the parent meter, multiplier, unit and sampling interval for every node in the hierarchy. If submeters do not reconcile with the main meter, investigate technical losses, unmetered loads, clock shifts and measurement errors separately; the difference is not automatically theft or a savings opportunity." } },
      { heading: { tr: "Veri kalitesi enerji analizinden önce gelir", en: "Data quality comes before energy analytics" }, body: { tr: "Beklenen zaman ızgarasına göre eksik, yinelenen ve sırası bozuk kayıtlar işaretlenmelidir. Negatif tüketim, fiziksel kapasiteyi aşan değer, donmuş sayaç, ani çarpan değişimi ve saat sapması için ayrı kurallar gerekir. Tahmini veri ham ölçümün üzerine yazılmaz; yöntem ve güven seviyesiyle ayrı tutulur. Bakım, duruş, ürün değişimi ve kapasite artışı gibi olaylar zaman çizelgesine eklenmezse model normal operasyonu yanlış öğrenebilir. Analiz kapsamı; geçerli kayıt yüzdesini ve dışlanan aralıkları sonuçla birlikte göstermelidir.", en: "Flag missing, duplicate and out-of-order records against the expected time grid. Negative consumption, values beyond physical capacity, frozen meters, multiplier changes and clock drift need separate rules. Estimated data must not overwrite raw measurements; retain it with method and confidence. If maintenance, shutdowns, product changes and capacity additions are absent from the timeline, a model can learn the wrong definition of normal operation. Every result should state valid-data coverage and excluded intervals." } },
      { heading: { tr: "Baz yük, pik ve normalize edilmiş EnPI", en: "Baseload, peaks and normalised EnPIs" }, body: { tr: "Toplam kWh, üretim değiştiğinde performansı tek başına açıklamaz. Ürün başına kWh, çalışma saati başına tüketim, üretim dışı baz yük, maksimum talep ve belirli yardımcı sistemlerin payı daha anlamlı göstergelerdir. Ürün karması, hava, vardiya ve çalışma süresi gibi ilgili değişkenler normalizasyon modeline açıkça eklenmelidir. Modelin referans dönemi ile raporlama dönemi aynı ölçüm sınırını kullanmalı; proses değişikliği olduğunda baz çizgisi güncelleme kuralı uygulanmalıdır. Düşük tüketim her zaman daha iyi performans değildir: üretim kaybı da kWh'yi azaltabilir.", en: "Total kWh alone cannot explain performance when output changes. Energy per unit, consumption per operating hour, non-production baseload, maximum demand and utility-system shares are more meaningful indicators. Relevant variables such as product mix, weather, shift and operating time should be explicit in the normalisation model. Baseline and reporting periods must share a boundary, with a documented adjustment rule after process change. Lower consumption is not always better performance: lost production can reduce kWh too." } },
      { heading: { tr: "Reaktif enerji, harmonik ve trafo kayıpları", en: "Reactive energy, harmonics and transformer losses" }, body: { tr: "Güç kalitesi sinyalleri enerji verimliliğinden ayrı ama ilişkili bir çalışma alanıdır. Düşük güç faktörü daha yüksek akım ve kapasite kullanımı yaratabilir; harmonikler ekipman ısınması ve ölçüm sorunlarıyla ilişkili olabilir; trafo boşta ve yük kayıpları farklı davranır. Tek bir taşınabilir ölçümle kalıcı sonuç çıkarılmamalıdır. Ölçüm noktası, cihaz sınıfı, örnekleme süresi, yük durumu ve yürürlükteki teknik/tarife sınırı doğrulanmalıdır. Kompanzasyon veya filtre yatırımı, önce güvenlik ve koruma koordinasyonu içeren yetkin mühendislik incelemesine tabi olmalıdır.", en: "Power quality is distinct from, but related to, energy efficiency. Low power factor can raise current and capacity use; harmonics may contribute to heating and measurement problems; transformer no-load and load losses behave differently. A single portable measurement is not a durable conclusion. Verify the measurement point, instrument class, sampling period, load state and applicable technical or tariff boundary. Compensation or filtering investment requires competent engineering review, including safety and protection coordination." } },
      { heading: { tr: "Alarmdan iş emrine ve kanıta", en: "From alert to work order and evidence" }, body: { tr: "Alarm yalnızca bir eşik ihlalidir; iyileştirme için sorumlu, öncelik, hedef süre ve kapanış kanıtı gerekir. İyi bir olay kaydı başlangıç-bitiş zamanını, etkilenen sayaçları, üretim durumunu, olası nedenleri ve uygulanan işlemi taşır. Kök neden doğrulanmadan tasarruf tutarı yazılmamalıdır. Örneğin gece baz yükü artışı; kaçak, açık kalan ekipman, planlı temizlik veya üretim kaydı eksikliğinden kaynaklanabilir. Önce fiziksel kontrol, sonra veri kontrolü, ardından karşılaştırma dönemi seçilir. Aynı alarm tekrarlanıyorsa eşik değil süreç gözden geçirilmelidir.", en: "An alert is only a threshold breach; improvement requires an owner, priority, response target and closure evidence. A useful incident record includes start and end time, affected meters, production state, candidate causes and the action taken. Do not book a saving before confirming root cause. A higher night baseload, for example, could reflect leakage, equipment left on, planned cleaning or missing production context. Perform physical verification first, data verification second and comparison-period selection third. If the alert repeats, review the process rather than merely moving the threshold." } },
      { heading: { tr: "Tasarruf nasıl doğrulanır?", en: "How to verify a saving" }, body: { tr: "Uygulama öncesi referans dönem seçilir, enerji kullanımını etkileyen üretim ve hava gibi değişkenler kaydedilir, sonra uygulama sonrası aynı sınırda beklenen tüketim hesaplanır. Tasarruf, ölçülen tüketim ile uygun koşullara normalize edilmiş beklenen tüketim arasındaki farktır; yalnızca önceki aya göre düşüş değildir. Belirsizlik, veri kapsama oranı, uygulama maliyeti ve kalıcılık süresi rapora eklenmelidir. Sonuç işletme, finans ve bakım ekibi tarafından aynı tanım üzerinden okunabiliyorsa aksiyon denetlenebilir hale gelir. Büyük yatırımlarda bağımsız ölçme ve doğrulama planı tercih edilmelidir.", en: "Choose a pre-action reference period, record variables such as production and weather, then calculate expected post-action consumption within the same boundary. A saving is the difference between measured use and expected use normalised to appropriate conditions—not merely a fall from the previous month. Report uncertainty, data coverage, implementation cost and persistence period. The action becomes auditable when operations, finance and maintenance read the result under the same definition. For material investments, use an independent measurement and verification plan." } },
    ],
    takeaways: { tr: ["Sayaç hiyerarşisi ve veri kalitesi analizden önce doğrulanmalıdır.", "Enerji performansı üretim ve diğer ilgili değişkenlerle normalize edilmelidir.", "Alarm, sahiplik ve uygulama sonrası doğrulama olmadan tasarruf değildir."], en: ["Validate meter hierarchy and data quality before analytics.", "Normalise energy performance for production and relevant variables.", "An alert is not a saving without ownership and post-action verification."] },
    sources: [
      { label: "ISO — ISO 50001 Energy management systems", url: "https://www.iso.org/iso-50001-energy-management.html" },
      { label: "ISO — ISO 50006 Energy performance", url: "https://www.iso.org/standard/79367.html" },
      { label: "U.S. Department of Energy — 50001 Ready", url: "https://navigator.lbl.gov/" },
      { label: "IEC — Power quality measurement methods", url: "https://webstore.iec.ch/en/publication/68642" },
    ],
  },
  {
    slug: "iso-50001-energy-baseline-enpi",
    category: { tr: "ISO 50001 ve Performans", en: "ISO 50001 and Performance" },
    title: { tr: "ISO 50001 Enerji Baz Çizgisi ve EnPI Uygulama Rehberi", en: "ISO 50001 Energy Baseline and EnPI Implementation Guide" },
    description: { tr: "Ölçüm sınırı, ilgili değişken, statik faktör, baz çizgisi, EnPI ve güncelleme kurallarını denetlenebilir biçimde kurun.", en: "Build auditable measurement boundaries, relevant variables, static factors, baselines, EnPIs and adjustment rules." },
    intro: { tr: "Enerji baz çizgisi geçmiş tüketimin rastgele bir ortalaması değildir; belirli bir ölçüm sınırı ve koşul altında performansı karşılaştırmak için kurulan referanstır. EnPI ise bu performansı yönetime taşıyan göstergedir. İkisi açık veri ve değişiklik kuralları olmadan kullanıldığında üretim düşüşünü tasarruf, kapasite artışını verimsizlik gibi gösterebilir.", en: "An energy baseline is not an arbitrary average of historical consumption; it is a reference built for a defined boundary and set of conditions. An EnPI carries that performance into management. Without explicit data and adjustment rules, the pair can mislabel lost production as savings or capacity expansion as inefficiency." },
    publishedAt: "2026-08-26",
    updatedAt: "2026-09-02",
    sections: [
      { heading: { tr: "Önce amaç ve enerji kapsamı", en: "Start with purpose and energy scope" }, body: { tr: "Baz çizgisinin hangi kararı destekleyeceği yazılmalıdır: yıllık yönetim hedefi, ekipman iyileştirmesi, proje doğrulaması veya bütçe. Tesis sınırı, enerji türü, ana ve alt sayaçlar, dahil edilen prosesler ve raporlama aralığı belgelenir. Elektrik, doğal gaz ve buhar farklı dönüşüm ve ölçüm belirsizlikleri taşıdığı için tek bir toplamda kaybolmamalıdır. Önemli enerji kullanımları belirlenirken büyüklük kadar değişkenlik ve iyileştirme potansiyeli de değerlendirilir. Veri sahibi ve gösterge sahibi ayrı olabilir; sorumluluklar açık atanmalıdır.", en: "Write down the decision the baseline supports: annual management target, equipment improvement, project verification or budget. Document the site boundary, energy type, main and submeters, included processes and reporting interval. Electricity, gas and steam have different conversions and uncertainties and should not disappear into one unexplained total. When identifying significant energy uses, consider variability and improvement potential as well as magnitude. Data ownership and indicator ownership may differ; assign both explicitly." } },
      { heading: { tr: "Referans dönem nasıl seçilir?", en: "How to choose a reference period" }, body: { tr: "Dönem, normal çalışma koşullarını ve yeterli mevsim/üretim çeşitliliğini temsil etmelidir. Büyük duruş, sayaç arızası veya olağan dışı sipariş karışımı içeren kayıtlar otomatik silinmez; etkisi açıklanır ve dışlama ölçütü önceden tanımlanır. Çok kısa dönem mevsimselliği yakalayamaz, çok eski dönem ise güncel prosesi temsil etmeyebilir. Veri tamamlığı, değişken aralığı ve proses kararlılığı birlikte değerlendirilir. Referans dönem seçildikten sonra ham veri anlık olarak değiştirilemez; düzeltmeler sürüm ve gerekçeyle izlenir.", en: "The period should represent normal operation and enough seasonal or production variation. Major shutdowns, meter failures or unusual order mixes are not silently deleted; explain their effect and define exclusion criteria in advance. A period that is too short misses seasonality, while an old period may no longer represent the process. Assess data completeness, variable range and process stability together. Once selected, baseline data should not change silently; corrections require version and rationale." } },
      { heading: { tr: "İlgili değişken ve statik faktör ayrımı", en: "Relevant variables versus static factors" }, body: { tr: "Üretim miktarı, derece-gün, çalışma saati veya ürün karması dönemden döneme değişerek enerji kullanımını etkiliyorsa ilgili değişkendir. Bina alanı, ekipman kapasitesi veya proses tasarımı daha kalıcı olup değiştiğinde baz çizgisini yapısal olarak etkileyen statik faktör olabilir. Her korelasyon modele alınmaz; fiziksel anlam, veri kalitesi ve gelecekte bulunabilirlik aranır. Model, geçmiş veriye çok iyi uyup yeni dönemde başarısız olabilir. Basit, açıklanabilir ve karar için yeterli model; karmaşık ama denetlenemeyen modele çoğu zaman tercih edilir.", en: "Production volume, degree days, operating hours or product mix may be relevant variables because they change between periods and influence energy use. Floor area, installed capacity or process design may be static factors whose change structurally affects the baseline. Not every correlation belongs in the model; require physical meaning, data quality and future availability. A model can fit history perfectly and fail in a new period. A simple, explainable model that supports the decision is often preferable to a complex but unauditable one." } },
      { heading: { tr: "EnPI seçimi ve örnek", en: "Selecting an EnPI with an example" }, body: { tr: "Bir EnPI, sorumlu ekibin etkileyebileceği performansı göstermelidir. kWh/ürün basit ve anlaşılırdır, fakat sabit baz yük yüksekse düşük üretimde yanıltıcı olabilir. Bu durumda enerji = baz yük + birim başına değişken tüketim gibi regresyon modeli daha adil karşılaştırma sağlar. Örneğin model belirli üretim ve hava koşulunda 120 MWh beklerken ölçüm 112 MWh ise fark 8 MWh'dir; fakat model belirsizliği, ölçüm kapsamı ve proses olayı kontrol edilmeden bu değer doğrulanmış tasarruf değildir. Gösterge tanımı formül, birim, sıklık, veri sahibi ve hedefle birlikte yayımlanmalıdır.", en: "An EnPI should represent performance the responsible team can influence. kWh per unit is simple, but it can mislead at low output when baseload is material. A model such as energy equals baseload plus variable use per unit may provide a fairer comparison. If the model expects 120 MWh under given production and weather conditions and measurement is 112 MWh, the difference is 8 MWh; it is not a verified saving until model uncertainty, measurement coverage and process events are checked. Publish the indicator with formula, unit, frequency, data owner and target." } },
      { heading: { tr: "Baz çizgisi ne zaman güncellenir?", en: "When to adjust the baseline" }, body: { tr: "Kapasite artışı, proses değişikliği, yeni ürün, sayaç sınırının değişmesi veya uzun süreli çalışma rejimi dönüşümü karşılaştırmayı anlamsızlaştırabilir. Güncelleme tetikleyicileri uygulama öncesinde tanımlanmalıdır. Eski ve yeni model, geçiş tarihi, gerekçe ve geçmiş raporlara etkisi saklanır. Yalnızca hedef tutmadığı için baz çizgisini değiştirmek performans yönetimini bozar. Küçük rutin dalgalanmalar normalizasyon modeliyle, yapısal değişiklikler ise resmi baz çizgisi revizyonuyla ele alınır. Yönetim gözden geçirmesi hem gösterge sonucunu hem de yöntemin hâlâ uygun olup olmadığını sorgulamalıdır.", en: "Capacity expansion, process redesign, a new product, changed meter boundary or a durable operating-regime shift can invalidate comparison. Define adjustment triggers before they occur. Retain the old and new model, transition date, rationale and impact on prior reports. Changing the baseline simply because a target was missed destroys performance management. Handle routine variation through normalisation and structural change through a formal baseline revision. Management review should challenge both the indicator result and whether the method remains suitable." } },
      { heading: { tr: "Denetim için tutulacak kanıt", en: "Evidence to retain for audit" }, body: { tr: "Ölçüm noktası listesi, kalibrasyon veya doğrulama kaydı, ham zaman serisi, eksik veri günlüğü, değişken kaynakları, model sürümü, dışlama nedenleri, baz dönem ve sorumlu onayları tek kanıt zincirinde tutulmalıdır. Dashboard ekran görüntüsü tek başına yeterli değildir; sonucun yeniden hesaplanabilmesi gerekir. Her rapor, kullanılan veri kapanış tarihini ve sonradan gelen revizyonların nasıl yönetileceğini belirtmelidir. Aksiyon kaydı beklenen etkiyi, gerçekleşen tarihi, maliyeti ve doğrulama sonucunu bağlamalıdır. Bu düzen ISO yaklaşımını günlük operasyonla ilişkilendirir.", en: "Keep the meter list, calibration or validation records, raw time series, missing-data log, variable sources, model version, exclusion rationale, baseline period and approvals in one evidence chain. A dashboard screenshot is not enough; the result must be reproducible. Each report should state the data cut-off and how later revisions are handled. The action record should connect expected effect, implementation date, cost and verification outcome. This turns the ISO approach into an operational method rather than a reporting exercise." } },
    ],
    takeaways: { tr: ["Baz çizgisi tanımlı sınır ve koşullar için referanstır.", "EnPI fiziksel anlamı olan ve sorumlunun etkileyebildiği performansı göstermelidir.", "Revizyon, dışlama ve veri işlemleri yeniden üretilebilir bir kanıt zincirinde tutulmalıdır."], en: ["A baseline is a reference for a defined boundary and conditions.", "An EnPI should have physical meaning and reflect controllable performance.", "Keep adjustments, exclusions and data treatment in a reproducible evidence chain."] },
    sources: [
      { label: "ISO — ISO 50001:2018", url: "https://www.iso.org/standard/69426.html" },
      { label: "ISO — ISO 50006:2023", url: "https://www.iso.org/standard/79367.html" },
      { label: "U.S. Department of Energy — 50001 Ready Navigator", url: "https://navigator.lbl.gov/" },
    ],
  },
  {
    slug: "energy-demand-forecasting",
    category: { tr: "Enerji Tahminleme", en: "Energy Forecasting" },
    title: { tr: "Enerji Talep ve Yenilenebilir Üretim Tahmini Nasıl Kurulur?", en: "How to Build Energy Demand and Renewable Generation Forecasts" },
    description: { tr: "Tahmin ufku, veri hazırlığı, referans model, zaman serisi doğrulaması, hata ölçümü ve operasyonel izleme adımlarını uygulayın.", en: "Apply forecast-horizon, data-preparation, baseline-model, time-series validation, error measurement and operational monitoring practices." },
    intro: { tr: "İyi tahmin, en karmaşık modeli seçmek değil; belirli bir karar için doğru ufukta, zamanında ve belirsizliği bilinen sonuç üretmektir. Fabrika yükü ile güneş/rüzgâr üretimi farklı fiziksel değişkenlere dayanır, ancak veri sızıntısı, yanlış doğrulama ve model kayması gibi ortak riskleri paylaşır. Bu rehber iki kullanım için uygulanabilir bir geliştirme ve işletme düzeni sunar.", en: "A good forecast is not the most complex model; it is a timely result at the right horizon for a defined decision, with known uncertainty. Factory load and solar or wind output depend on different physical variables, yet share risks such as leakage, invalid validation and model drift. This guide provides an applied development and operating method for both." },
    publishedAt: "2026-08-26",
    updatedAt: "2026-09-02",
    sections: [
      { heading: { tr: "Karar, ufuk ve çözünürlük", en: "Decision, horizon and resolution" }, body: { tr: "Gün öncesi tedarik, vardiya planlama, pik talep yönetimi ve yıllık bütçe aynı tahmini kullanmamalıdır. Her kullanım için tahminin üretildiği zaman, kapsadığı gelecek ufku, zaman çözünürlüğü ve gerekli teslim süresi yazılır. Saatlik operasyon için yıllık model; yıllık bütçe için dakikalık model gereksizdir. Kayıp fonksiyonu da karara göre değişir: pik saat hatası, toplam enerji hatasından daha pahalı olabilir. Başarı ölçütü yalnızca ortalama hata değil, doğru zamanda mevcut olma ve karar üzerinde ölçülebilir etki üretmedir.", en: "Day-ahead procurement, shift planning, peak management and annual budgeting should not share one forecast. For each use case, state issue time, future horizon, time resolution and delivery deadline. An annual model does not serve hourly operations, while minute-level output is unnecessary for annual budgeting. The loss function also depends on the decision: missing a peak may cost more than the same error off-peak. Success includes availability at decision time and measurable operational impact, not only average statistical error." } },
      { heading: { tr: "Özellik zamanını doğru kurun", en: "Build feature timing correctly" }, body: { tr: "Talep modelinde yakın geçmiş yük, saat, gün türü, tatil, sıcaklık, üretim planı ve vardiya kullanılabilir. Yenilenebilir üretimde ışınım, rüzgâr hızı/yönü, sıcaklık, türbin veya inverter kullanılabilirliği ve kesinti bilgisi önemlidir. Fakat tahmin anında bilinmeyen gerçekleşmiş hava veya üretim değerini eğitimde kullanmak veri sızıntısı yaratır. Her değişkenin ne zaman kullanılabilir olduğu ve hangi sürümünün kullanılacağı belgelenmelidir. Sayaç ve hava serileri ortak zaman dilimine getirilmeli; bakım/duruş olayları rastgele aykırı değer gibi silinmemelidir.", en: "Demand models may use recent load, hour, day type, holidays, temperature, production plan and shift. Renewable models depend on irradiance, wind speed and direction, temperature, equipment availability and curtailment. Using realised weather or output that would not be known at forecast issue time creates leakage. Document when every feature becomes available and which forecast vintage is used. Align meters and weather on one time axis, and do not delete maintenance or shutdown events as arbitrary outliers." } },
      { heading: { tr: "Basit referans model olmadan ilerlemeyin", en: "Do not proceed without a simple baseline" }, body: { tr: "Dünkü aynı saat, geçen haftanın aynı günü, mevsimsel ortalama veya fiziksel güç eğrisi gibi basit yöntemler zorunlu referanstır. Yeni model bu referansı tutarlı biçimde aşmıyorsa ek karmaşıklık operasyonel değer üretmiyor olabilir. Karşılaştırma aynı dönem, aynı veri kullanılabilirliği ve aynı hata metriğiyle yapılmalıdır. Rastgele eğitim-test bölmesi zaman serisinde gelecek bilgisini geçmişe sızdırabilir; ileri yürüyen doğrulama tercih edilir. Aşırı sıcak, tatil, düşük üretim ve ekipman arızası gibi rejimler ayrı hata dilimlerinde raporlanmalıdır.", en: "Yesterday's same hour, last week's same day, a seasonal average or a physical power curve is a required baseline. If a new model does not consistently beat it, added complexity may not create operational value. Compare on the same period, information set and metric. Random train-test splits can leak future information into the past; use rolling or forward validation. Report errors separately for regimes such as extreme weather, holidays, low output and equipment outages." } },
      { heading: { tr: "Hata metriğini iş etkisine bağlayın", en: "Connect error metrics to business impact" }, body: { tr: "MAE hatanın ortalama büyüklüğünü kolay yorumlatır; RMSE büyük hataları daha fazla cezalandırır; yüzde tabanlı metrikler gerçek değer sıfıra yaklaştığında bozulabilir. Tek bir toplam skor, sistematik pik kaçırmayı veya yanlı tahmini gizleyebilir. Saat, sezon, yük seviyesi ve tahmin ufkuna göre hata dağılımı incelenmelidir. P10/P50/P90 gibi olasılık tahminleri belirsizliği karar verene taşıyabilir, ancak bu aralıkların kapsama oranı ayrıca kalibre edilmelidir. En iyi metrik, hatanın gerçek maliyeti veya riskine en yakın olandır.", en: "MAE is easy to interpret as average magnitude; RMSE penalises large misses more; percentage metrics can break down near zero actuals. One aggregate score may hide systematic peak misses or bias. Inspect error by hour, season, load level and horizon. Probabilistic outputs such as P10, P50 and P90 can communicate uncertainty, but their observed coverage must be calibrated. The most useful metric approximates the real cost or risk of error." } },
      { heading: { tr: "Üretime alma ve güvenli geri dönüş", en: "Deployment and safe fallback" }, body: { tr: "Model sürümü, eğitim veri kapanış tarihi, özellik listesi ve çalışma ortamı kaydedilir. Tahmin zamanında veri gelmezse sessizce sıfır üretmek yerine durum işaretlenmeli; basit referans modele geri dönüş kuralı bulunmalıdır. Çıktı, gerçekleşen değer geldiğinde otomatik eşleştirilir ve hata panosu güncellenir. Gecikme, başarısız çalışma, eksik özellik ve aralık dışı girdi de model kalitesi kadar izlenir. İnsan operatör, tahminin hangi koşullarda güvenilmez olabileceğini ve elle müdahalenin nasıl kayda alınacağını bilmelidir.", en: "Record model version, training-data cut-off, feature list and runtime environment. If an input is unavailable at issue time, flag the state instead of silently producing zero, and define fallback to a simple baseline. When actuals arrive, join them automatically and update error monitoring. Track latency, failed runs, missing features and out-of-range inputs alongside model accuracy. Operators should know when the forecast may be unreliable and how to record a manual override." } },
      { heading: { tr: "Model kayması ve yeniden eğitim", en: "Drift and retraining" }, body: { tr: "Yeni hat, tarife, vardiya, ekipman veya hava veri sağlayıcısı ilişkinin değişmesine neden olabilir. Yalnızca hata eşiği aşıldığında otomatik yeniden eğitim yapmak hatalı veriyi modele taşıyabilir. Önce veri şeması, sayaç ve proses değişikliği incelenir; sonra yeniden eğitim kararı verilir. Eski ve yeni model gölge çalıştırma veya kontrollü karşılaştırmayla test edilir. Üretimde hangi sürümün ne zaman aktif olduğu ve neden değiştirildiği saklanır. Tahmin sistemi, model dosyasından çok veri, izleme, geri dönüş ve sorumluluk sürecidir.", en: "A new line, tariff, shift, asset or weather provider can change learned relationships. Automatically retraining whenever an error threshold is crossed may feed bad data into the model. Inspect schema, meter and process changes first, then decide on retraining. Compare old and new models through shadow operation or a controlled evaluation. Retain which version was active, when and why it changed. A forecasting system is a process of data, monitoring, fallback and accountability—not merely a model file." } },
    ],
    takeaways: { tr: ["Tahmin ufku ve hata metriği gerçek karara göre seçilmelidir.", "Zaman serisi doğrulaması ve basit referans model zorunludur.", "Üretim sistemi veri eksikliği, kayma, geri dönüş ve sürüm izini yönetmelidir."], en: ["Choose horizon and error metric for the actual decision.", "Time-series validation and a simple baseline are mandatory.", "Production must manage missing inputs, drift, fallback and version history."] },
    sources: [
      { label: "U.S. EIA — Short-Term Energy Outlook", url: "https://www.eia.gov/outlooks/steo/" },
      { label: "NREL — Solar Power Data for Integration Studies", url: "https://www.nrel.gov/grid/solar-power-data.html?print=" },
    ],
  },
  {
    slug: "cbam-carbon-border-adjustment",
    category: { tr: "Karbon ve SKDM", en: "Carbon and CBAM" },
    title: { tr: "SKDM/CBAM ve Kurumsal Emisyon Verisi: Uygulama Çerçevesi", en: "CBAM and Corporate Emissions Data: An Implementation Framework" },
    description: { tr: "Organizasyon ve ürün sınırı, faaliyet verisi, emisyon faktörü, kanıt zinciri ve mevzuat güncelliğini birlikte yönetin.", en: "Manage organisational and product boundaries, activity data, emission factors, evidence and regulatory currency together." },
    intro: { tr: "Karbon hesabında en büyük risk çoğu zaman çarpma işlemi değil; yanlış sınır, yanlış dönem veya kanıtsız veri kullanmaktır. SKDM/CBAM gibi düzenlemeler ürün ve tesis verisini belirli kurallarla isterken kurumsal Scope 1–2–3 envanteri farklı bir amaç ve sınır taşıyabilir. Bu rehber, veri omurgasını kurarken bu çalışmaların birbirine karıştırılmaması için pratik bir yol sunar.", en: "The largest risk in carbon accounting is often not multiplication but the wrong boundary, period or unsupported input. A mechanism such as CBAM asks for product and installation data under specific rules, while a corporate Scope 1, 2 and 3 inventory has a different purpose and boundary. This guide provides a practical way to build a shared data backbone without treating these outputs as interchangeable." },
    publishedAt: "2026-08-26",
    updatedAt: "2026-09-02",
    sections: [
      { heading: { tr: "Önce raporlama amacını ayırın", en: "Separate the reporting purpose first" }, body: { tr: "Kurumsal sera gazı envanteri şirketin sahiplik veya kontrol yaklaşımına göre emisyon kaynaklarını kapsamlara ayırır. Ürün karbon hesabı belirli ürün sistem sınırını ve tahsis yöntemini izler. SKDM/CBAM ise yürürlükteki AB düzenlemeleri, kapsamdaki mal ve kurulum tanımları üzerinden raporlama ister. Aynı elektrik faturası bu üç çalışmada kullanılabilir, fakat dönem, tahsis ve kabul edilen emisyon faktörü farklı olabilir. Veri modelinde rapor türü, kapsam sürümü ve düzenleyici referans zorunlu alan olmalıdır; bir çalışmanın sonucunu diğerine doğrudan kopyalamayın.", en: "A corporate greenhouse-gas inventory classifies sources under an ownership or control approach. Product carbon work follows a product system boundary and allocation method. CBAM reporting follows current EU rules and definitions for covered goods and installations. The same electricity bill may support all three, yet period, allocation and accepted factor can differ. Make report type, boundary version and regulatory reference mandatory fields in the data model; do not copy one output directly into another." } },
      { heading: { tr: "Faaliyet verisi ve kanıt zinciri", en: "Activity data and evidence chain" }, body: { tr: "Yakıt, elektrik, proses girdisi ve üretim miktarı gibi faaliyet verileri kaynak sistemle bağını korumalıdır. Fatura toplamı, sayaç zaman serisi ve üretim kaydı aynı döneme uzlaştırılır; birim dönüşümü açıkça saklanır. Eksik değer tahmin edildiyse yöntem, sorumlu ve güven seviyesi yazılır. Belge yalnızca dosya deposunda bulunmamalı; hesap satırı hangi kanıta dayandığını göstermelidir. Düzeltme yapıldığında önceki değer silinmez, sürüm geçmişi tutulur. Bu yaklaşım doğrulayıcının örneklem seçmesini ve hesabın yeniden üretilmesini kolaylaştırır.", en: "Activity data—fuel, electricity, process inputs and output—should retain its connection to the source system. Reconcile invoice totals, interval meters and production records to the same period, and store unit conversions explicitly. If a value is estimated, record method, owner and confidence. Evidence should not merely exist in a file store; each calculation line should point to the supporting item. When corrected, retain the previous value in version history. This allows a verifier to sample and reproduce the calculation." } },
      { heading: { tr: "Emisyon faktörü nasıl seçilir?", en: "How to select an emission factor" }, body: { tr: "Faktörün güncel olması tek başına yeterli değildir; yakıt/teknoloji, coğrafya, dönem, alt-üst ısıl değer, gaz kapsamı ve birim faaliyeti temsil etmelidir. Mümkün olan durumda doğrulanmış tedarikçi veya tesis verisi, sonra ülke/sektör özel faktörü, en son genel varsayılan değerlendirilir; ancak ilgili raporlama kuralı bu sırayı değiştirebilir. Her faktör için yayımlayan kurum, yayın yılı, tablo/sürüm, birim, CO₂e dönüşüm seti ve uygulanan dönüşüm kaydedilir. Faktör güncellendiğinde geçmiş yılı sessizce yeniden yazmak yerine belgeli yeniden hesaplama politikası uygulanır.", en: "Recency alone is insufficient. A factor must represent fuel or technology, geography, period, heating-value convention, gas coverage and activity unit. Where rules allow, consider verified supplier or installation data, then country or sector factors, and generic defaults last—but the applicable reporting method may prescribe a different hierarchy. Record publisher, publication year, table or version, unit, CO₂e conversion set and transformations. When a factor changes, follow a documented recalculation policy rather than silently rewriting history." } },
      { heading: { tr: "Scope 1, 2 ve 3'te çift sayımı yönetin", en: "Manage double counting across Scopes 1, 2 and 3" }, body: { tr: "Scope 1 sahip olunan veya kontrol edilen kaynaklardaki doğrudan emisyonları; Scope 2 satın alınan enerji üretiminden doğan dolaylı emisyonları; Scope 3 ise değer zinciri kategorilerini kapsar. Kurumsal sınır içindeki bir yakıt hem Scope 1'e hem satın alınan ürünler kategorisine yazılmamalıdır. Scope 2 konum bazlı ve piyasa bazlı sonuçlar farklı veri ve sözleşme kanıtı gerektirir. İlk yılda tüm Scope 3 kategorilerine eşit ayrıntı vermek yerine önemlilik taraması, veri sahibi ve geliştirme planı oluşturmak daha denetlenebilir olabilir.", en: "Scope 1 covers direct emissions from owned or controlled sources; Scope 2 covers indirect emissions from purchased energy; Scope 3 covers value-chain categories. A fuel inside the organisational boundary should not also be counted as purchased goods. Location-based and market-based Scope 2 results require different data and contractual evidence. In a first year, a documented materiality screen, data owner and improvement plan may be more auditable than pretending every Scope 3 category has equal precision." } },
      { heading: { tr: "SKDM verisinde dönem ve mevzuat sürümü", en: "Period and regulatory version in CBAM data" }, body: { tr: "SKDM kapsamı, hesap yöntemi, varsayılan değerler ve raporlama yükümlülükleri zaman içinde değişebilir. Bu nedenle sabit bir internet makalesine dayanarak beyan hazırlanmaz. Her raporlama dönemi için Avrupa Komisyonu'nun güncel resmi rehberi, mevzuat metni, kapsamdaki CN kodları ve varsa yetkili makam açıklamaları kontrol edilir. Sistem; dönem, ürün, tesis, yöntem sürümü, doğrulama durumu ve sorumlu alanlarını saklamalıdır. Bu sayfa genel veri yönetişimi açıklar; güncel yükümlülük veya hukuki uygunluk görüşü vermez.", en: "CBAM scope, calculation methods, default values and obligations can change. A declaration should therefore never rely on a static web article. For each reporting period, check current European Commission guidance, legal text, covered CN codes and competent-authority notices where applicable. The system should retain period, product, installation, method version, verification status and owner. This page explains general data governance; it does not provide a current legal determination." } },
      { heading: { tr: "Kalite kontrol ve yönetim onayı", en: "Quality control and management approval" }, body: { tr: "Toplamlar kaynak belgeye, alt toplamlar organizasyon ve ürün sınırına, faktörler onaylı kütüphaneye bağlanır. Birim kontrolü, dönem uzlaştırması, olağan dışı yoğunluk, yinelenen kayıt ve eksik kanıt için otomatik kurallar çalışabilir; yine de maddi istisnalar insan incelemesine gider. Hazırlayan ve onaylayan rol ayrımı, değişiklik günlüğü ve veri kapanış tarihi raporda görünür olmalıdır. Belirsizlik yüksekse tek kesin sayı yerine aralık veya veri kalite sınıfı sunulur. Yönetim sonucu yalnızca yayınlamaz; veri boşlukları için sorumlu ve tamamlanma tarihi atar.", en: "Tie totals to source documents, subtotals to organisational and product boundaries, and factors to an approved library. Automated rules can check units, period reconciliation, unusual intensity, duplicates and missing evidence, while material exceptions still go to human review. Show preparer and approver separation, change log and data cut-off in the report. Where uncertainty is high, present a range or data-quality class rather than false precision. Management should assign an owner and completion date to data gaps, not merely approve publication." } },
    ],
    takeaways: { tr: ["Kurumsal envanter, ürün hesabı ve SKDM aynı çıktı değildir.", "Her hesap satırı faaliyet verisi, faktör, dönem ve kanıta bağlanmalıdır.", "Güncel SKDM yükümlülüğü yalnızca resmi mevzuat ve yetkili rehberle doğrulanmalıdır."], en: ["Corporate inventory, product accounting and CBAM are not the same output.", "Connect every calculation line to activity data, factor, period and evidence.", "Verify current CBAM obligations only against official law and guidance."] },
    sources: [
      { label: "European Commission — Carbon Border Adjustment Mechanism", url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism_en" },
      { label: "European Commission — CBAM legislation and guidance", url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-legislation-and-guidance_en" },
      { label: "GHG Protocol — Corporate Standard", url: "https://ghgprotocol.org/corporate-standard" },
      { label: "GHG Protocol — Scope 2 Guidance", url: "https://ghgprotocol.org/scope-2-guidance" },
    ],
  },
  {
    slug: "smart-metering-ami-infrastructure",
    category: { tr: "Sayaç, OT ve Veri Mimarisi", en: "Metering, OT and Data Architecture" },
    title: { tr: "Enerji Analizörü, RS485/Modbus, AMI ve OT Entegrasyon Rehberi", en: "Energy Analysers, RS485/Modbus, AMI and OT Integration Guide" },
    description: { tr: "Saha keşfi, register doğrulama, zaman senkronizasyonu, veri modeli, ağ ayrımı ve güvenli devreye alma adımlarını planlayın.", en: "Plan field discovery, register validation, time synchronisation, data modelling, network separation and secure commissioning." },
    intro: { tr: "Enerji verisi projesinin güvenilirliği buluttaki grafikten önce sahadaki ölçüm zincirinde belirlenir. Aynı 'Modbus destekli' etiketi, iki cihazın doğrudan ve doğru haberleşeceği anlamına gelmez. Fiziksel katman, seri iletişim ayarları, register haritası, ölçek katsayısı, byte sırası ve güvenlik sınırı birlikte doğrulanmalıdır.", en: "The reliability of an energy-data project is determined in the field measurement chain before a cloud chart. The same 'Modbus supported' label does not guarantee two devices will communicate correctly. Physical layer, serial settings, register map, scaling, byte order and security boundary must be verified together." },
    publishedAt: "2026-08-26",
    updatedAt: "2026-09-02",
    sections: [
      { heading: { tr: "Keşif: belge, topoloji ve sorumluluk", en: "Discovery: documents, topology and ownership" }, body: { tr: "Her cihaz için üretici/model, yazılım sürümü, haberleşme kılavuzu, register haritası, sayaç çarpanı ve mevcut ağ topolojisi toplanır. RS485 hattında kablo güzergâhı, ekranlama/topraklama yaklaşımı, sonlandırma, bias, cihaz adresleri ve master sayısı doğrulanır. Modbus TCP tarafında IP planı, port, yönlendirme ve ağ bölgesi kaydedilir. SCADA, EMS, DMS ve AMI gibi sistem adları rolü tek başına açıklamaz; verinin sahibi, komut yetkisi ve arıza sorumlusu matriste belirtilir. Üretici belgesi görülmeden register numarası veya veri tipi tahmin edilmez.", en: "For every device, collect manufacturer and model, firmware, communication manual, register map, meter multiplier and current topology. On RS485, verify cable route, shielding and grounding approach, termination, bias, device addresses and number of masters. For Modbus TCP, record IP plan, port, routing and network zone. Labels such as SCADA, EMS, DMS and AMI do not by themselves define responsibility; map data ownership, command authority and fault response. Never guess a register number or data type without the exact device documentation." } },
      { heading: { tr: "Register ve değer doğrulama", en: "Register and value validation" }, body: { tr: "Devreye almada önce cihaz ekranındaki anlık değer ile okunan ham register karşılaştırılır. Adres gösteriminin sıfır veya bir tabanlı olması, holding/input register türü, signed/unsigned tanımı, 16/32 bit genişlik, word-byte sırası ve ölçek katsayısı tek tek test edilir. kW, kWh, kvar, kvarh, gerilim ve akım birimleri şemada zorunlu tutulur. Kümülatif enerji sayacı güç gibi toplanmaz; sayaç sıfırlaması ve taşma davranışı kaydedilir. En az düşük, normal ve yüksek yük koşulunda örnek doğrulama yapılır.", en: "During commissioning, compare the live device display with the raw register value first. Test zero- or one-based address notation, holding versus input register, signedness, 16- or 32-bit width, word and byte order, and scaling individually. Make units such as kW, kWh, kvar, kvarh, voltage and current mandatory in the schema. A cumulative energy counter is not aggregated like power; record reset and rollover behaviour. Validate samples at low, normal and high load where practical." } },
      { heading: { tr: "Zaman, kalite bayrağı ve sayaç kimliği", en: "Time, quality flags and meter identity" }, body: { tr: "Gateway zamanı, cihaz zamanı ve merkez zamanı karıştırılırsa aynı olay farklı saatlerde görünebilir. Güvenilir NTP kaynağı, saat dilimi ve yaz saati kuralı belirlenir; ham zaman damgası korunur. Her kayıt değer kadar kalite bayrağı, kaynak cihaz, register sürümü ve alma zamanı taşımalıdır. İletişim kesildiğinde son değeri yeni ölçüm gibi tekrar etmek yerine stale durumu işaretlenir. Sayaç değişiminde fiziksel konum aynı kalsa bile cihaz kimliği ve endeks sürekliliği ayrı olay olarak yönetilir. Bu meta veriler kök neden analizinin temelidir.", en: "If gateway, device and central time are mixed, one event can appear at different hours. Define a trusted NTP source, time zone and daylight-saving rule while retaining the raw timestamp. Every record should carry a quality flag, source device, register-map version and ingestion time as well as the value. On communication loss, mark data stale instead of repeating the last value as a new measurement. When a meter is replaced, manage device identity and index continuity as an explicit event even if the physical location is unchanged. This metadata underpins root-cause analysis." } },
      { heading: { tr: "OT ağ sınırı ve en az yetki", en: "OT network boundary and least privilege" }, body: { tr: "Saha cihazını doğrudan internete açmak entegrasyon değildir. OT ile BT/bulut arasında tanımlı ağ bölgeleri, güvenlik duvarı kuralları, izinli yönler ve izlenen bir edge geçidi kullanılmalıdır. Yalnızca gereken hedef, port ve protokol açılır; varsayılan parolalar kaldırılır; uzaktan erişim süreli ve kayıtlı olur. Salt okunur enerji verisi akışı ile kontrol komutu aynı güven seviyesinde tasarlanmamalıdır. Güncelleme, yedekleme, sertifika/anahtar yenileme ve olay müdahale sorumlusu devreye alma öncesinde belirlenir. Güvenlik tasarımı saha kullanılabilirliğini ve güvenliği birlikte korumalıdır.", en: "Putting a field device directly on the internet is not integration. Use defined zones, firewall rules, allowed directions and a monitored edge gateway between OT and IT or cloud. Open only required destinations, ports and protocols; remove default credentials; make remote access time-bound and logged. Read-only energy telemetry and control commands should not share one trust model. Define update, backup, credential rotation and incident-response ownership before commissioning. Security must protect field availability and safety as well as confidentiality." } },
      { heading: { tr: "Devreye alma kabul testleri", en: "Commissioning acceptance tests" }, body: { tr: "Kabul planı bağlantının 'çalışıyor' olmasından fazlasını test eder: cihaz keşfi, doğru değer, birim, zaman damgası, veri kaybı sonrası toparlanma, yeniden başlatma, ağ kesintisi, yinelenen paket, kimlik doğrulama hatası ve beklenen sorgu yükü. Ana sayaç ile alt toplamlar belirli bir dönem için uzlaştırılır; farkın kabul toleransı önceden yazılır. Paket yakalama veya cihaz logu gerektiğinde kişisel/sır verinin korunması planlanır. Sonuçlar cihaz ve register sürümüyle imzalanmış kabul kaydına dönüşür. Başarısız test açık risk ve sorumluyla kapatılır.", en: "Acceptance tests go beyond 'connected': verify device discovery, value, unit, timestamp, recovery after loss, restart, network interruption, duplicate packets, authentication failure and expected polling load. Reconcile the main meter and submeters over a defined period with a pre-agreed tolerance. If packet captures or device logs are needed, plan protection of personal or confidential data. Results become an acceptance record tied to device and register-map version. A failed test closes only with an explicit risk decision and owner." } },
      { heading: { tr: "Bakım ve değişiklik yönetimi", en: "Maintenance and change management" }, body: { tr: "Saha entegrasyonu devreye alma gününde bitmez. Yazılım güncellemesi, IP değişimi, sayaç değişimi, yeni register haritası veya ağ politikası veri zincirini bozabilir. Yapılandırma envanteri ve bağımlılık listesi güncel tutulur; değişiklik önce test ortamında veya kontrollü pencerede denenir. Veri kalite panosu iletişim sürekliliği, stale kayıt, beklenmeyen sıfır, saat kayması ve ana-alt sayaç farkını izler. Kritik alarmın kime, hangi sürede ve hangi kanıtla kapatılacağı tanımlıdır. Bu disiplin olmadan gelişmiş analitik, güvenilmez girişleri yalnızca daha hızlı işler.", en: "Field integration does not end at commissioning. Firmware, IP, meter, register-map or network-policy changes can break the chain. Maintain configuration inventory and dependencies, and test changes in a controlled environment or window. Monitor communication continuity, stale data, unexpected zeros, clock drift and main-to-submeter reconciliation. Define who receives a critical alert, expected response time and closure evidence. Without this discipline, advanced analytics merely processes unreliable inputs faster." } },
    ],
    takeaways: { tr: ["Cihaz ve register bilgisi üretici belgesiyle doğrulanmadan tahmin edilmemelidir.", "Değer kadar birim, zaman, kalite ve kaynak kimliği de saklanmalıdır.", "OT entegrasyonu ağ ayrımı, en az yetki ve kabul testleriyle devreye alınmalıdır."], en: ["Never guess device or register details without manufacturer documentation.", "Retain unit, time, quality and source identity with every value.", "Commission OT integration with segmentation, least privilege and acceptance tests."] },
    sources: [
      { label: "Modbus Organization — Protocol specifications", url: "https://www.modbus.org/specs.php" },
      { label: "NIST — Smart Grid National Coordination", url: "https://www.nist.gov/programs-projects/smart-grid-national-coordination" },
      { label: "CISA — Industrial Control Systems", url: "https://www.cisa.gov/topics/industrial-control-systems" },
      { label: "IEC — Smart grids", url: "https://www.iec.ch/smartgrid" },
    ],
  },
  {
    slug: "battery-energy-storage-bess",
    category: { tr: "Depolama ve Yenilenebilir Enerji", en: "Storage and Renewable Energy" },
    title: { tr: "BESS Boyutlandırma ve Yenilenebilir Enerji Entegrasyon Rehberi", en: "BESS Sizing and Renewable Energy Integration Guide" },
    description: { tr: "Güç/enerji ayrımı, kullanım senaryosu, kayıp, çevrim, kısıt ve finansal senaryolarla batarya kararını kurun.", en: "Frame battery decisions through power/energy separation, use case, losses, cycling, constraints and financial scenarios." },
    intro: { tr: "Batarya depolama sistemi yalnızca bir MWh kapasite seçimi değildir. Aynı enerji kapasitesi; inverter gücü, deşarj süresi, verim, kullanılabilir doluluk aralığı, sıcaklık, çevrim ve şebeke kısıtına göre çok farklı sonuç verir. Boyutlandırma önce kullanım senaryosunu ve fiziksel zaman serisini tanımlar, sonra teknoloji ve finansı seçer.", en: "A battery energy storage system is not merely an MWh selection. The same energy capacity produces very different outcomes depending on inverter power, duration, efficiency, usable state-of-charge window, temperature, cycling and grid constraints. Sizing should define the use case and physical time series first, then select technology and finance." },
    publishedAt: "2026-08-26",
    updatedAt: "2026-09-02",
    sections: [
      { heading: { tr: "Kullanım senaryosunu tek cümlede yazın", en: "State the use case in one sentence" }, body: { tr: "Pik talep azaltma, güneş öz tüketimini artırma, sıfır enjeksiyon, kesinti yedekleme, fiyat arbitrajı ve yan hizmet aynı tasarımı gerektirmez. Hedef; hangi sinyale göre şarj/deşarj yapılacağını, gerekli tepki süresini, olay süresini ve başarı metriğini içermelidir. Örneğin '15 dakikalık maksimum talebi ayda 500 kW azalt' güç odaklıdır; 'öğlen 2 MWh güneş fazlasını akşama taşı' enerji ve süre odaklıdır. Birden fazla gelir veya fayda birleştirilecekse aynı anda çakışan doluluk gereksinimleri açıkça simüle edilmelidir.", en: "Peak reduction, solar self-consumption, zero export, backup, price arbitrage and ancillary services do not require the same design. The objective should identify the dispatch signal, response time, event duration and success metric. 'Reduce monthly 15-minute peak demand by 500 kW' is power-focused; 'shift 2 MWh of midday solar surplus into the evening' is energy- and duration-focused. If stacking revenue or benefits, explicitly simulate conflicts in state-of-charge requirements." } },
      { heading: { tr: "MW ile MWh'yi ayrı boyutlandırın", en: "Size MW and MWh separately" }, body: { tr: "İnverter gücü bataryanın anlık şarj/deşarj sınırını, enerji kapasitesi ise bu gücü ne kadar süre sürdürebileceğini belirler. 1 MW / 2 MWh sistem teorik olarak iki saatliktir; ancak kullanılabilir doluluk aralığı, yardımcı tüketim, dönüşüm kaybı ve güç düşümü teslim edilebilir enerjiyi azaltır. Şebeke bağlantı kapasitesi ve trafo sınırı da inverter etiketinden daha düşük olabilir. Boyutlandırma, en kötü tek olaya değil seçilen zaman serisinde çok sayıda olayın süresi ve sıklığına dayanmalıdır. Güç ve enerji marjları ayrı gerekçelendirilir.", en: "Inverter MW limits instantaneous charge and discharge, while MWh determines how long that power can be sustained. A 1 MW/2 MWh system is nominally two-hour, but usable state-of-charge range, auxiliary load, conversion loss and power derating reduce delivered energy. Grid connection and transformer limits may be below the inverter nameplate. Size against event duration and frequency across the selected time series, not one worst-looking event. Justify power and energy margins separately." } },
      { heading: { tr: "Zaman serisi simülasyonu", en: "Time-series simulation" }, body: { tr: "En az bir temsilî yıl için tesis yükü, güneş/rüzgâr üretimi, fiyat veya talep sinyali ve varsa kesinti kısıtı aynı zaman ekseninde birleştirilir. Her adımda doluluk, şarj/deşarj gücü, verim ve bağlantı sınırı uygulanır. Geleceği bilen kusursuz kontrol algoritması gerçek işletme sonucunu abartabilir; karar anında mevcut tahminlerle simülasyon yapılmalıdır. Eksik veri ve olağan dışı duruşlar raporlanır. Sonuç yalnızca yıllık kazanç değil, çevrim sayısı, kullanılmayan enerji, karşılanamayan olay ve maksimum güç/enerji gereksinimini göstermelidir.", en: "For at least one representative year, align facility load, solar or wind output, price or demand signal and any export constraint. At each interval apply state of charge, charge/discharge power, efficiency and connection limits. A perfect-control simulation that knows the future can overstate real performance; use information available at dispatch time. Report missing data and unusual shutdowns. Outputs should include cycles, curtailed or unserved energy, missed events and maximum power and energy requirements—not only annual value." } },
      { heading: { tr: "Degradasyon, garanti ve kullanılabilirlik", en: "Degradation, warranty and availability" }, body: { tr: "Batarya kapasitesi takvim yaşı, çevrim derinliği, C-rate, sıcaklık ve kimyaya göre zamanla azalır. Garanti belgesindeki enerji throughput, çevrim, kalan kapasite ve işletme koşulları finansal modelle aynı varsayımları kullanmalıdır. HVAC ve yangın güvenliği yardımcı tüketimi ile planlı/plansız bakım kullanılabilirliği etkiler. İlk yıl kazancını tüm ömre sabit taşımak hatalıdır; kapasite ve verim düşüşü yıllık modellenir. Hücre değişimi, inverter yenileme ve bertaraf/geri dönüşüm sorumluluğu da toplam sahip olma maliyetine eklenmelidir.", en: "Capacity declines with calendar age, depth of discharge, C-rate, temperature and chemistry. Warranty terms for throughput, cycles, retained capacity and operating conditions must align with the financial model. HVAC and fire-safety auxiliaries plus planned and unplanned maintenance affect availability. Do not carry first-year value unchanged through the project life; model annual capacity and efficiency decline. Include cell replacement, inverter renewal and end-of-life responsibility in total cost of ownership." } },
      { heading: { tr: "Güneş, PPA ve sertifika sınırları", en: "Solar, PPA and certificate boundaries" }, body: { tr: "Batarya güneş öz tüketimini artırabilir, ancak enerjinin hukuki veya çevresel niteliğini kendiliğinden değiştirmez. PPA fiyat yapısı, teslim profili, dengesizlik, kesinti ve sertifika devri ayrı sözleşme konularıdır. YEK-G veya başka enerji niteliği belgelerinde ihraç, transfer ve itfa kayıtları tüketim iddiasıyla eşleşmelidir. Saatlik fiziksel eşleşme ile yıllık sözleşmesel eşleşme aynı şey değildir. Depolama sonrası yenilenebilirlik iddiası yapılacaksa şarj kaynağı, ölçüm sınırı, kayıp ve izlenebilirlik yöntemi ilgili kurallara göre doğrulanmalıdır.", en: "A battery can increase solar self-consumption, but it does not automatically change the legal or environmental attribute of energy. PPA price structure, delivery profile, imbalance, curtailment and certificate transfer are separate contractual topics. YEK-G or other attribute records for issuance, transfer and redemption should reconcile with the consumption claim. Hourly physical matching is not the same as annual contractual matching. Any renewable claim after storage requires verification of charge source, measurement boundary, losses and traceability under the applicable rules." } },
      { heading: { tr: "Finansal senaryo ve karar kapısı", en: "Financial scenarios and decision gates" }, body: { tr: "Gelir veya kaçınılan maliyet; düşük, orta ve yüksek fiyat/talep senaryolarında simüle edilir. CAPEX yanında finansman, bağlantı, inşaat, yazılım, bakım, sigorta, yardımcı tüketim, kapasite kaybı ve vergi etkileri belirtilir. Aynı faydanın iki kez sayılmaması gerekir; örneğin aynı deşarj hem pik azaltma hem tam arbitraj enerjisi olarak yazılamaz. Karar kapıları veri yeterliliği, şebeke izni, güvenlik tasarımı, tedarikçi garantisi ve duyarlılık sonucunu içerir. Nihai yatırım kararı, sahaya özel elektrik ve yangın güvenliği mühendisliği olmadan verilmemelidir.", en: "Model revenue or avoided cost under low, central and high price or demand scenarios. Beyond CAPEX, state financing, interconnection, civil works, software, maintenance, insurance, auxiliary load, capacity fade and tax effects. Do not double count one benefit—the same discharge cannot simultaneously be full peak reduction and full arbitrage energy. Decision gates should cover data sufficiency, grid permission, safety design, supplier warranty and sensitivities. Final investment requires site-specific electrical and fire-safety engineering." } },
    ],
    takeaways: { tr: ["BESS gücü ve enerji kapasitesi farklı kullanım gereksinimlerine göre ayrı seçilir.", "Boyutlandırma, gerçek zaman serisi ve karar anındaki bilgiyle simüle edilmelidir.", "Degradasyon, güvenlik, şebeke ve sözleşme sınırları finansal sonuçla birlikte değerlendirilmelidir."], en: ["Select BESS power and energy separately for the use case.", "Size with a real time series and information available at dispatch time.", "Evaluate degradation, safety, grid and contract boundaries with financial results."] },
    sources: [
      { label: "NREL — System Advisor Model: Battery Storage", url: "https://sam.nrel.gov/index.php?Itemid=360&id=94&option=com_content&view=article" },
      { label: "U.S. Department of Energy — Energy Storage", url: "https://www.energy.gov/oe/energy-storage" },
      { label: "European Commission — Power Purchase Agreements", url: "https://energy.ec.europa.eu/publications/commission-recommendation-removing-barriers-development-power-purchase-agreements-and-other-energy_en" },
      { label: "EPİAŞ — YEK-G", url: "https://yekgnedir.epias.com.tr/" },
    ],
  },
];

export const insightSlugs = insights.map((article) => article.slug);

export function getInsight(slug: string) {
  return insights.find((article) => article.slug === slug);
}

export function getReadMinutes(article: InsightArticle, locale: InsightLocale) {
  const text = [
    article.title[locale],
    article.description[locale],
    article.intro[locale],
    ...article.sections.flatMap((section) => [section.heading[locale], section.body[locale]]),
    ...article.takeaways[locale],
  ].join(" ");
  return Math.max(1, Math.ceil(text.trim().split(/\s+/).length / 200));
}
